name: master_test
on: 
  push:
    branchs:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - run:   go test -v 